use_frameworks!

platform :ios, '10.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'CXSwiftKit_Example' do
  pod 'CXSwiftKit', :path => '../'
  
  # Keychain
  pod 'DYFSwiftKeychain'
  
  # -- TEST --
  # Kingfisher
  pod 'Kingfisher'
  # SDWebImage
  pod 'SDWebImage'
  
  # RxSwift
  pod 'RxSwift'
  # RxCocoa
  pod 'RxCocoa'
  # Moya
  pod 'Moya'
  # HandyJSON
  pod 'HandyJSON'
  
  # KafkaRefresh
  pod 'KafkaRefresh'
  # MJRefresh
  pod 'MJRefresh'
  
  # SVProgressHUD
  pod 'SVProgressHUD'
  # SwiftMessages
  pod 'SwiftMessages'
  # Toaster
  pod 'Toaster'
  # Toast_Swift
  pod 'Toast-Swift', '~> 5.0.1'
  
  # Starscream
  pod 'Starscream'
  
  # DZNEmptyDataSet
  pod 'DZNEmptyDataSet'
  
  # SVGA
  #pod 'SVGAPlayer'
  
  # OverlayController
  pod 'OverlayController'
  
  target 'CXSwiftKit_Tests' do
    inherit! :search_paths
  end
  
end
